### ISSUE TITLE
Add verbosity setting to package and drop warning in makeNiceTiff

### ISSUE THREAD

**Issue by ethanplunkett** [ethanplunkett/rasterPrep#2]
Requested by @bwcompton:

> I would love to see the warning in makeNiceTif removed. I can't imagine anyone would use the type option without reading the warning in the help. 

> On a related note, a chatter or verbose option would be nice in both warpToReference and makeNiceTif. The command lines sure are nice to be able to see when debugging, but I prefer my subroutines to run silently. As it is, there's so much junk on the screen I can't tell what's going on.

**Comment by ethanplunkett** [comment]
I think having a verbose setting for the package as a whole might be the way to go.  I could turn it on for debugging but most users are probably rather not be spammed with text.

**Comment by bwcompton** [comment]
Fancy!

Usually, the top-level function should chatter but everything it calls should STFU unless the user is debugging and has asked for verbose mode. My calling function does it's own chattering (silent user-called functions that take a long time suck), but it does occur to me that someone might call it in a loop, and then I'd want my function to STFU and the function that calls it to supply the only chatter. I'm not sure what the best way to implement this would be.
